id: docker-proxy-build-denied
name: Docker Proxy Test - build-denied
task_behaviors:
  smoke:
    hooks:
      - id: run-docker-test
        command: |
          bash "$DOCKER_PROXY_TEST_ROOT/docker-proxy-test.sh"
    name: smoke
