package api_test

import (
	"testing"

	"github.com/novshi-tech/boid/internal/orchestrator"
	"github.com/novshi-tech/boid/testutil"
)

func createTaskForTest(t *testing.T, ts *testutil.TestServer, projectID, title string) orchestrator.Task {
	t.Helper()
	req := map[string]any{
		"project_id": projectID,
		"title":      title,
		"behavior":   "planning",
	}
	var task orchestrator.Task
	if err := ts.Client.Do("POST", "/api/tasks", req, &task); err != nil {
		t.Fatalf("create task %q: %v", title, err)
	}
	return task
}

func TestCreateTask_WithSpecifiedID(t *testing.T) {
	ts := testutil.NewTestServer(t)
	createProjectWithBehavior(t, ts, "proj-id-test", "ID Test")

	req := map[string]any{
		"id":         "my-specific-task-id",
		"project_id": "proj-id-test",
		"title":      "Task with specified ID",
		"behavior":   "planning",
	}
	var task orchestrator.Task
	if err := ts.Client.Do("POST", "/api/tasks", req, &task); err != nil {
		t.Fatalf("POST /api/tasks: %v", err)
	}
	if task.ID != "my-specific-task-id" {
		t.Fatalf("ID = %q, want %q", task.ID, "my-specific-task-id")
	}

	// Verify via GET
	var got orchestrator.Task
	if err := ts.Client.Do("GET", "/api/tasks/my-specific-task-id", nil, &got); err != nil {
		t.Fatalf("GET /api/tasks/my-specific-task-id: %v", err)
	}
	if got.ID != "my-specific-task-id" {
		t.Fatalf("GET ID = %q, want %q", got.ID, "my-specific-task-id")
	}
}

func TestCreateTask_IDOmitted_AutoGenerated(t *testing.T) {
	ts := testutil.NewTestServer(t)
	createProjectWithBehavior(t, ts, "proj-uuid-test", "UUID Test")

	req := map[string]any{
		"project_id": "proj-uuid-test",
		"title":      "Task without explicit ID",
		"behavior":   "planning",
	}
	var task orchestrator.Task
	if err := ts.Client.Do("POST", "/api/tasks", req, &task); err != nil {
		t.Fatalf("POST /api/tasks: %v", err)
	}
	if task.ID == "" {
		t.Fatal("expected auto-generated UUID, got empty string")
	}
	if len(task.ID) != 36 {
		t.Fatalf("expected UUID length 36, got %d: %s", len(task.ID), task.ID)
	}
}

func TestCreateTask_WithDependsOn(t *testing.T) {
	ts := testutil.NewTestServer(t)
	createProjectWithBehavior(t, ts, "proj-dep-test", "Dep Test")

	dep1 := createTaskForTest(t, ts, "proj-dep-test", "Dep 1")
	dep2 := createTaskForTest(t, ts, "proj-dep-test", "Dep 2")

	req := map[string]any{
		"project_id": "proj-dep-test",
		"title":      "Main task",
		"behavior":   "planning",
		"depends_on": []string{dep1.ID, dep2.ID},
	}
	var task orchestrator.Task
	if err := ts.Client.Do("POST", "/api/tasks", req, &task); err != nil {
		t.Fatalf("POST /api/tasks: %v", err)
	}
	if len(task.DependsOn) != 2 {
		t.Fatalf("DependsOn = %v (len %d), want 2 items", task.DependsOn, len(task.DependsOn))
	}

	// Verify DependsOn is loaded on subsequent GET
	var got orchestrator.Task
	if err := ts.Client.Do("GET", "/api/tasks/"+task.ID, nil, &got); err != nil {
		t.Fatalf("GET /api/tasks/%s: %v", task.ID, err)
	}
	if len(got.DependsOn) != 2 {
		t.Fatalf("GET DependsOn = %v (len %d), want 2 items", got.DependsOn, len(got.DependsOn))
	}
	found1, found2 := false, false
	for _, id := range got.DependsOn {
		if id == dep1.ID {
			found1 = true
		}
		if id == dep2.ID {
			found2 = true
		}
	}
	if !found1 || !found2 {
		t.Fatalf("DependsOn = %v, want contains [%s, %s]", got.DependsOn, dep1.ID, dep2.ID)
	}
}

func TestCreateTask_DependsOn_NotFound_ReturnsError(t *testing.T) {
	ts := testutil.NewTestServer(t)
	createProjectWithBehavior(t, ts, "proj-dep-notfound", "Dep NotFound")

	req := map[string]any{
		"project_id": "proj-dep-notfound",
		"title":      "Task with bad dep",
		"behavior":   "planning",
		"depends_on": []string{"nonexistent-task-id-that-does-not-exist"},
	}
	err := ts.Client.Do("POST", "/api/tasks", req, nil)
	if err == nil {
		t.Fatal("expected error for nonexistent depends_on, got nil")
	}
}
