#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$E2E_WORKSPACE_DIR/app"

# Set up workspace for new schema (PR4 hard cutover).
WS_SLUG="host-command-smoke"
mkdir -p "$XDG_CONFIG_HOME/boid/workspaces"
cat > "$XDG_CONFIG_HOME/boid/workspaces/${WS_SLUG}.yaml" <<YAML
kits:
  - host-ops
YAML

e2e_log "registering project from $PROJECT_DIR"
e2e_run "$E2E_BIN_DIR/boid" project add "$PROJECT_DIR"
e2e_run "$E2E_BIN_DIR/boid" workspace assign "e2e-host-ops" "$WS_SLUG"

e2e_log "creating smoke task"
task_create_output="$("$E2E_BIN_DIR/boid" task create <<'YAML'
project_id: e2e-host-ops
title: Host Command Smoke
behavior: smoke
YAML
)"
printf '%s\n' "$task_create_output"
task_id="$(printf '%s\n' "$task_create_output" | sed -n 's/^task created: \([0-9a-f-]*\) (.*/\1/p')"
[[ -n "$task_id" ]] || e2e_fail "failed to parse task id"

start_payload="$E2E_STATE_DIR/start-payload.json"
cat >"$start_payload" <<'EOF'
{"artifact":{}}
EOF

e2e_log "starting task $task_id"
e2e_run "$E2E_BIN_DIR/boid" action send --task "$task_id" --type start --payload "$start_payload"

e2e_log "waiting for task completion"
task_json="$("$E2E_BIN_DIR/boid-e2e" wait-task-status --timeout 15s --interval 100ms "$task_id" done)"
printf '%s\n' "$task_json"

grep -F '"status":"done"' <<<"$task_json" >/dev/null || e2e_fail "task did not reach done"
grep -F '"pr_url":"https://example.invalid/pr/123"' <<<"$task_json" >/dev/null || e2e_fail "task payload missing fake pr url"
grep -F '"verification"' <<<"$task_json" >/dev/null || e2e_fail "task payload missing verification"

[[ -f "$E2E_STATE_DIR/fake-gh.log" ]] || e2e_fail "missing fake gh log"
[[ -f "$E2E_STATE_DIR/fake-systemctl.log" ]] || e2e_fail "missing fake systemctl log"

grep -F 'args=pr create --title E2E PR --body generated by e2e' "$E2E_STATE_DIR/fake-gh.log" >/dev/null || e2e_fail "gh pr create was not invoked"
grep -F 'args=--user restart boid' "$E2E_STATE_DIR/fake-systemctl.log" >/dev/null || e2e_fail "systemctl restart was not invoked"

[[ -f "$E2E_STATE_DIR/fake-hook-cmd.log" ]] || e2e_fail "missing fake-hook-cmd log (hook did not invoke broker-mediated hostcmd)"
grep -F 'args=--hook-ran' "$E2E_STATE_DIR/fake-hook-cmd.log" >/dev/null || e2e_fail "fake-hook-cmd was not invoked with --hook-ran from the hook"

# host_commands.alias-echo.path = echo-target: the declared short name
# ("alias-echo") differs from the sandbox-visible file's basename
# ("echo-target"), same shape as this repo's own host_commands.run-e2e ->
# e2e/run.sh. This is the 5a-2 regression guard (docs/plans/
# phase5-shim-and-task-context.md, codex review Minor finding on 5a-1): if
# the shim ever resolves its broker-facing command name from argv0's
# basename alone instead of BOID_HOST_COMMAND_NAMES, this dispatch fails
# with "command not allowed: echo-target" and the hook (set -eu) aborts.
[[ -f "$E2E_STATE_DIR/fake-alias-echo.log" ]] || e2e_fail "missing fake-alias-echo log (aliased host command did not resolve to its declared short name)"
grep -F 'args=--alias-ran' "$E2E_STATE_DIR/fake-alias-echo.log" >/dev/null || e2e_fail "echo-target (host_commands.alias-echo) was not invoked with --alias-ran from the hook"
