id: docker-proxy-volume-create
name: Docker Proxy Test - volume-create
task_behaviors:
  smoke:
    hooks:
      - id: run-docker-test
        command: |
          bash "$DOCKER_PROXY_TEST_ROOT/docker-proxy-test.sh"
    name: smoke
