#!/usr/bin/env bash
# kit-init-basic: boid kit init の sandbox 起動 + 正常終了を検証する。
#
# 戦略: BOID_DEFAULT_HARNESS=shell を設定し、 Argv=["boid-kit-init"] を
# シェルアダプタに渡す。 ProfileInit sandbox の PATH には boid バイナリと
# 同じディレクトリ (E2E_BIN_DIR) が先頭に置かれるため、 その場所に
# 偽の boid-kit-init スクリプトを置けばサンドボックス内で実行される。
#
# 偽スクリプトは kits ディレクトリ配下に最小限の kit.yaml を書き exit 0
# するだけ。 post-run の secret scan は clean に通過し、 CLI が
# "generated kits: fake-kit" を出力して正常終了する。
set -euo pipefail

# -------------------------------------------------------------------
# 1. Fake harness: sandbox の PATH は E2E_BIN_DIR が先頭なので
#    そこに boid-kit-init スクリプトを置く。
# -------------------------------------------------------------------
FAKE_KIT_NAME="fake-kit"
KITS_DIR="$XDG_DATA_HOME/boid/kits"

cat > "$E2E_BIN_DIR/boid-kit-init" <<'SCRIPT'
#!/usr/bin/env bash
# Fake boid-kit-init: called by the shell adapter inside the ProfileInit sandbox.
# It creates a minimal kit.yaml so scanNewKitDirs succeeds, then exits 0.
set -euo pipefail

KITS_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/boid/kits"
mkdir -p "$KITS_DIR/fake-kit"
cat > "$KITS_DIR/fake-kit/kit.yaml" <<'YAML'
name: fake-kit
description: "E2E fake kit generated by kit-init-basic scenario"
YAML

echo "fake boid-kit-init: wrote fake-kit/kit.yaml"
exit 0
SCRIPT
chmod +x "$E2E_BIN_DIR/boid-kit-init"
e2e_log "placed fake boid-kit-init in $E2E_BIN_DIR"

# -------------------------------------------------------------------
# 2. Set BOID_DEFAULT_HARNESS=shell so the prompt is skipped and the
#    shell adapter is selected.  The env var is scoped to this subshell
#    and propagates to the child boid process via os.Environ().
# -------------------------------------------------------------------
export BOID_DEFAULT_HARNESS=shell

# -------------------------------------------------------------------
# 3. Run boid kit init and capture output.
# -------------------------------------------------------------------
e2e_log "running boid kit init with BOID_DEFAULT_HARNESS=shell"
kit_init_out="$("$E2E_BIN_DIR/boid" kit init 2>&1)"
printf '%s\n' "$kit_init_out"

# -------------------------------------------------------------------
# 4. Assert expected output strings.
# -------------------------------------------------------------------
e2e_assert_contains "$kit_init_out" "default harness: shell"
e2e_log "OK: 'default harness: shell' found in output"

e2e_assert_contains "$kit_init_out" "generated kits: $FAKE_KIT_NAME"
e2e_log "OK: 'generated kits: $FAKE_KIT_NAME' found in output"

# -------------------------------------------------------------------
# 5. Assert the kit directory and kit.yaml were created on the host.
# -------------------------------------------------------------------
if [[ ! -d "$KITS_DIR/$FAKE_KIT_NAME" ]]; then
    e2e_fail "expected kit directory $KITS_DIR/$FAKE_KIT_NAME to exist"
fi
e2e_log "OK: kit directory exists"

if [[ ! -f "$KITS_DIR/$FAKE_KIT_NAME/kit.yaml" ]]; then
    e2e_fail "expected kit.yaml to exist at $KITS_DIR/$FAKE_KIT_NAME/kit.yaml"
fi
e2e_log "OK: kit.yaml exists"

e2e_log "kit-init-basic scenario completed successfully"
