#!/usr/bin/env bash
# kit-init-basic: boid kit init の sandbox 起動 + 正常終了を検証する。
#
# 戦略: BOID_DEFAULT_HARNESS=shell を設定し、 Argv=["boid-kit-init"] を
# シェルアダプタに渡す。
#
# ProfileInit sandbox はホスト root を ro-rbind するが、 /tmp は新規 tmpfs で
# 上書きされる。 boid バイナリは単体ファイルのみ bind されるため、 E2E_BIN_DIR
# 配下の他ファイルは sandbox 内から見えない。
#
# 代わりに: kits dir を sandbox に rw bind してあるので、 $KITS_DIR/bin/ に
# 偽の boid-kit-init を置く。 PATH には $KITS_DIR/bin が含まれるため sandbox
# 内から実行される。 bin/ を先に作成しておくことで listKitDirs の baseline
# snapshot に入り、 scanNewKitDirs が bin/ を新規 kit として誤検知しない。
#
# 偽スクリプトは $KITS_DIR/fake-kit/kit.yaml を書き exit 0 する。
# post-run の secret scan は clean に通過し、 CLI が
# "generated kits: fake-kit" を出力して正常終了する。
set -euo pipefail

# -------------------------------------------------------------------
# 1. Prepare kits dir and place fake boid-kit-init inside bin/.
#    Creating kitsDir/bin/ before running `boid kit init` ensures it
#    appears in the baseline snapshot (listKitDirs), so scanNewKitDirs
#    does not treat bin/ as a newly generated kit.
# -------------------------------------------------------------------
FAKE_KIT_NAME="fake-kit"
KITS_DIR="$XDG_DATA_HOME/boid/kits"
mkdir -p "$KITS_DIR/bin"

cat > "$KITS_DIR/bin/boid-kit-init" <<'SCRIPT'
#!/usr/bin/env bash
# Fake boid-kit-init: called by the shell adapter inside the ProfileInit sandbox.
# It creates a minimal kit.yaml so scanNewKitDirs succeeds, then exits 0.
set -euo pipefail

KITS_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/boid/kits"
mkdir -p "$KITS_DIR/fake-kit"
cat > "$KITS_DIR/fake-kit/kit.yaml" <<'YAML'
name: fake-kit
description: "E2E fake kit generated by kit-init-basic scenario"
YAML

echo "fake boid-kit-init: wrote fake-kit/kit.yaml"
exit 0
SCRIPT
chmod +x "$KITS_DIR/bin/boid-kit-init"
e2e_log "placed fake boid-kit-init in $KITS_DIR/bin"

# -------------------------------------------------------------------
# 2. Set BOID_DEFAULT_HARNESS=shell so the prompt is skipped and the
#    shell adapter is selected.  The env var is scoped to this subshell
#    and propagates to the child boid process via os.Environ().
# -------------------------------------------------------------------
export BOID_DEFAULT_HARNESS=shell

# -------------------------------------------------------------------
# 3. Run boid kit init and capture output.
# -------------------------------------------------------------------
e2e_log "running boid kit init with BOID_DEFAULT_HARNESS=shell"
kit_init_out="$("$E2E_BIN_DIR/boid" kit init 2>&1)"
printf '%s\n' "$kit_init_out"

# -------------------------------------------------------------------
# 4. Assert expected output strings.
# -------------------------------------------------------------------
e2e_assert_contains "$kit_init_out" "default harness: shell"
e2e_log "OK: 'default harness: shell' found in output"

e2e_assert_contains "$kit_init_out" "generated kits: $FAKE_KIT_NAME"
e2e_log "OK: 'generated kits: $FAKE_KIT_NAME' found in output"

# -------------------------------------------------------------------
# 5. Assert the kit directory and kit.yaml were created on the host.
# -------------------------------------------------------------------
if [[ ! -d "$KITS_DIR/$FAKE_KIT_NAME" ]]; then
    e2e_fail "expected kit directory $KITS_DIR/$FAKE_KIT_NAME to exist"
fi
e2e_log "OK: kit directory exists"

if [[ ! -f "$KITS_DIR/$FAKE_KIT_NAME/kit.yaml" ]]; then
    e2e_fail "expected kit.yaml to exist at $KITS_DIR/$FAKE_KIT_NAME/kit.yaml"
fi
e2e_log "OK: kit.yaml exists"

e2e_log "kit-init-basic scenario completed successfully"
