id: docker-proxy-container-network
name: Docker Proxy Test - container-network
task_behaviors:
  smoke:
    hooks:
      - id: run-docker-test
        command: |
          bash "$DOCKER_PROXY_TEST_ROOT/docker-proxy-test.sh"
    name: smoke
