id: docker-proxy-container-network
name: Docker Proxy Test - container-network
task_behaviors:
  smoke:
    hooks:
      - id: run-docker-test
        command: |
          bash ".boid/hooks/run-docker-test.sh"
    name: smoke
