id: docker-proxy-security-opt
name: Docker Proxy Test - security-opt
task_behaviors:
  smoke:
    hooks:
      - id: run-docker-test
        command: |
          bash "$DOCKER_PROXY_TEST_ROOT/docker-proxy-test.sh"
    name: smoke
