id: docker-proxy-security-opt
name: Docker Proxy Test - security-opt
task_behaviors:
  smoke:
    hooks:
      - id: run-docker-test
        command: |
          bash ".boid/hooks/run-docker-test.sh"
    name: smoke
