ALTER TABLE tasks ADD COLUMN transition TEXT NOT NULL DEFAULT '';
ALTER TABLE tasks ADD COLUMN traits TEXT NOT NULL DEFAULT '[]';
ALTER TABLE tasks ADD COLUMN readonly BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE tasks ADD COLUMN worktree BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE tasks ADD COLUMN branch_prefix TEXT NOT NULL DEFAULT '';
ALTER TABLE tasks ADD COLUMN base_branch TEXT NOT NULL DEFAULT '';
